# Site settings
title: Stephan's Blog
author: Stephan Dollberg
# author_avatar: https://gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=50
email: stephan.dollberg@gmail.com
description: My website and blog - a place to store my memories about computers, programming and other tech
baseurl: "" # optional
url: "https://dollberg.xyz"
#twitter_username: foo_bar
github_username: Stephan Dollberg
# github_repo: foo_bar/foo_bar.github.io
#google_analytics: UA-80085-YOUR-ID
disqus: stephansblog

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
